---
apiVersion: v1
kind: Template
labels:
  app: s2i-php-nginx-container
  template: s2i-php-nginx-container
message: |-
  The following build config has beend added s2i-php-nginx-${NGINX_VERSION}-container.
  You can use the image via the following imagestream:

  For more information about using this template, including OpenShift considerations, see https://github.com/disappear89/s2i-php-nginx-container.git
metadata:
  annotations:
    description: An BuildConfig for a customized s2i-nginx-container Image.
    iconClass: icon-php
    openshift.io/display-name: Nginx-S2i + PHP
    openshift.io/documentation-url: https://github.com/disappear89/s2i-php-nginx-container.git
    openshift.io/long-description: This template builds an extended image of the offical s2i-nginx-container
    to support also php s2i builds.
    openshift.io/provider-display-name: ThoBits
    tags: quickstart,php,nginx
    template.openshift.io/bindable: "false"
  creationTimestamp: null
  name: s2i-php-nginx-container
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: nginx-${NGINX_VERSION}-php-centos7
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: s2i-php-nginx-${NGINX_VERSION}-container
    creationTimestamp:
    labels:
      name: s2i-php-nginx-${NGINX_VERSION}-container
  spec:
    source:
      type: Git
      git:
        uri: https://github.com/disappear89/s2i-php-nginx-container.git
        ref: master
      contextDir: ${NGINX_VERSION}
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: nginx-${NGINX_VERSION}-php-centos7:latest
    resources: {}
  status:
    lastVersion: 0
parameters:
- displayName: Nginx-Version
  name: NGINX_VERSION
  required: true
  value: 1-12
